### ISSUE TITLE
Iopaint batch processing could auto paint??

### ISSUE THREAD

**Issue by wang3680** [Sanster/IOPaint#433]
many images need remove watermark ,those images's watermark in lower right corner .
can I auto remove watermark? thanks

**Comment by Sanster** [comment]
If the watermark remains fixed in its position, you may prepare a mask image and employ it to perform inpainting on all the images.

You can activate the option "Download Mask" in IOPaint. Once activated, the mask will be downloaded along with the inpainted results.

<img width="783" alt="截屏2024-01-25 18 26 02" src="https://github.com/Sanster/lama-cleaner/assets/3998421/af3388bc-d616-4696-aab1-3b93a5719454">

**Comment by Sanster** [comment]
https://www.iopaint.com/batch_process
