### ISSUE TITLE
outpainting workflow

### ISSUE THREAD

**Issue by wr4thful** [Sanster/IOPaint#471]
hi, im trying to outpaint this image
![2-1](https://github.com/Sanster/IOPaint/assets/143463195/e97c63da-fdea-4a83-abf1-94a5121b50f1)

but i keep getting this black bar result regardless of any changes that i made in  the model and configs.

**using `stable-diffusion-inpainting`**
![chrome_2024-03-05_02 34 46](https://github.com/Sanster/IOPaint/assets/143463195/4010fa26-4c8f-4f01-ba68-170632bbd3e1)

**using `powerpaint`**
![chrome_2024-03-05_02 31 05](https://github.com/Sanster/IOPaint/assets/143463195/b1ef7c31-a5d3-4549-b229-6235ab3df8ab)

as you can see both give same results. did i missed something crucial in the process or i picked the wrong model? whats the approach to do outpainting in my case? looking forward for any responses and help, thanks :)

**Comment by Sanster** [comment]
## Service startup parameters
If the generated result is black, you can try adding these two parameters when starting the service:
- --disable-nsfw-checker
- --no-half(Some graphics cards will produce black results without adding this parameter.)

## outpainting workflow

- I think `PowerPaint` and `runwayml/stable-diffusion-inpainting` cannot handle such high resolution, so it is recommended to switch to `diffusers/stable-diffusion-xl-1.0-inpainting-0.1`.

- Even when using `diffusers/stable-diffusion-xl-1.0-inpainting-0.1`, it is recommended to only outpaint one side, as shown in the picture.
<img width="1053" alt="image" src="https://github.com/Sanster/IOPaint/assets/3998421/9614800d-d048-4fab-8334-24cf574c70af">

- During testing your image, I found a bug in IOPaint. This has been fixed in version `iopaint==1.2.2`. Here are the results I obtained using the fixed version. The newly generated region has discoloration, I think it should be similar to the issue mentioned in this issue https://github.com/huggingface/diffusers/issues/5808, and there doesn't seem to be a good solution at the moment:
![309879155-e97c63da-fdea-4a83-abf1-94a5121b50f1_outpainting](https://github.com/Sanster/IOPaint/assets/3998421/7dc33f87-f3c7-485c-a665-917b7d655808)

prompt:
detailed background, best quality, 4k, dramatic cinematic perfect light, coherent, deep, detailed, very inspirational, intricate, beautiful, highly color set, real, complex, artistic, appealing, full, symmetry, great composition, sharp, fine detail, clear, focus, inspired, epic, spectacular, breathtaking, gorgeous, stunning, infinite, futuristic, professional, awarded

Other parameters.
<img width="310" alt="image" src="https://github.com/Sanster/IOPaint/assets/3998421/95d0460f-e9cb-4c81-bb9f-c05ad32799aa">

**Comment by wr4thful** [comment]
hey sorry for the late responses thanks for the feedback. i really appreciate it.
